import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="h-screen relative">
        {/* Фиксированный фон для всех страниц */}
        <div className="absolute inset-0 grid grid-cols-2 grid-rows-2">
          <div className="bg-pink-500"></div>
          <div className="bg-cyan-400"></div>
          <div className="bg-green-300"></div>
          <div className="bg-orange-400"></div>
        </div>
        {/* Контент страниц */}
        <div className="relative z-10 h-full flex items-center justify-center p-8">
          <div className="bg-white rounded-lg shadow-2xl p-16 max-w-2xl w-full text-center">
          {children}
          </div>
        </div>
      </div>
      </body>
    </html>
  );
}
